---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: streams-operatorgroup
  namespace: messaging-with-ocp-amq-streams
spec:
  targetNamespaces:
  - messaging-with-ocp-amq-streams
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: messaging-with-ocp-amq-streams
spec:
  channel: stable
  installPlanApproval: Automatic
  name: amq-streams
  source: redhat-operators
  sourceNamespace: openshift-marketplace